# Generated by Django 3.2.23 on 2023-12-15 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=124, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
