# Generated by Django 3.2.23 on 2023-12-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_of_user',
            field=models.CharField(
                choices=[('admin_users', 'Admin Usesrs')],
                default='admin_users',
                max_length=128,
            ),
        ),
    ]
